samples <- read.csv("SraRunTable.txt")
samples$condition <- sub("[0-9]+","",samples$Isolate)
samples <- samples[order(samples$condition),]
files <- file.path("quants",samples$Run,"quant.sf")
file.exists(files)
coldata <- data.frame(files=files, names=samples$Run, condition=samples$condition)
library(tximeta)
se <- tximeta(coldata)
gse <- summarizeToGene(se)
save(se, gse, file="tximeta_output.rda")
